
#ifndef GAMECUBE_CONTROLLER_EXPORT_H
#define GAMECUBE_CONTROLLER_EXPORT_H

#ifdef GAMECUBE_CONTROLLER_STATIC_DEFINE
#  define GAMECUBE_CONTROLLER_EXPORT
#  define GAMECUBE_CONTROLLER_NO_EXPORT
#else
#  ifndef GAMECUBE_CONTROLLER_EXPORT
#    ifdef gamecube_controller_EXPORTS
        /* We are building this library */
#      define GAMECUBE_CONTROLLER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define GAMECUBE_CONTROLLER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef GAMECUBE_CONTROLLER_NO_EXPORT
#    define GAMECUBE_CONTROLLER_NO_EXPORT 
#  endif
#endif

#ifndef GAMECUBE_CONTROLLER_DEPRECATED
#  define GAMECUBE_CONTROLLER_DEPRECATED __declspec(deprecated)
#endif

#ifndef GAMECUBE_CONTROLLER_DEPRECATED_EXPORT
#  define GAMECUBE_CONTROLLER_DEPRECATED_EXPORT GAMECUBE_CONTROLLER_EXPORT GAMECUBE_CONTROLLER_DEPRECATED
#endif

#ifndef GAMECUBE_CONTROLLER_DEPRECATED_NO_EXPORT
#  define GAMECUBE_CONTROLLER_DEPRECATED_NO_EXPORT GAMECUBE_CONTROLLER_NO_EXPORT GAMECUBE_CONTROLLER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef GAMECUBE_CONTROLLER_NO_DEPRECATED
#    define GAMECUBE_CONTROLLER_NO_DEPRECATED
#  endif
#endif

#endif /* GAMECUBE_CONTROLLER_EXPORT_H */
